@startuml Application_Patient

left to right direction

actor Patient
actor Administrateur as Admin

rectangle Application_Ortholib {
    usecase "Se connecter" as Connexion
    usecase "Passer le test" as PasserTest
    usecase "Refuser de passer le test" as RefuserTest
    usecase "Confirmer ses difficultés sans test" as ConfirmerDifficultesSansTest
    usecase "Validation des résultats" as ValidationResultat
    usecase "Orientation vers un niveau d’apprentissage" as OrientationNiveauApprentissage
    usecase "Choisir un orthophoniste" as ChoixOrthophoniste
    usecase "Accéder à l’espace patient" as EspacePatient
    usecase "Consulter les résultats et progrès" as ConsulterResultatsProgres
    usecase "Consulter les séances passées" as ConsulterSeancesPassees
    usecase "Accéder aux recommandations personnalisées" as AccederRecommandations
    usecase "Consulter et réaliser les exercices donnés" as ConsulterRéaliserExercices
    usecase "Télécharger des documents envoyés par l’orthophoniste" as TelechargerDocuments
    usecase "Consulter et modifier ses informations personnelles" as ConsulterModifierInfos
}

/' ACTORS -- USECASES '/

Patient -- Connexion
Patient -- PasserTest
Patient -- RefuserTest
Patient -- ConfirmerDifficultesSansTest
Patient -- ChoixOrthophoniste
Patient -- EspacePatient
Patient -- ConsulterResultatsProgres
Patient -- ConsulterSeancesPassees
Patient -- AccederRecommandations
Patient -- ConsulterRéaliserExercices
Patient -- TelechargerDocuments
Patient -- ConsulterModifierInfos

/' USECASES -- USECASES '/

Connexion <.. PasserTest : include
Connexion <.. RefuserTest : include
Connexion <.. ConfirmerDifficultesSansTest : include
PasserTest <.. ValidationResultat : include
ValidationResultat <.. OrientationNiveauApprentissage : include
OrientationNiveauApprentissage <.. ChoixOrthophoniste : include
ChoixOrthophoniste <.. EspacePatient : include
EspacePatient <.. ConsulterResultatsProgres : include
EspacePatient <.. ConsulterSeancesPassees : include
EspacePatient <.. AccederRecommandations : include
EspacePatient <.. ConsulterRéaliserExercices : include
EspacePatient <.. TelechargerDocuments : include
EspacePatient <.. ConsulterModifierInfos : include

@enduml
