@startuml VideoPresentation
actor Visiteur
participant PageAccueil
database BaseDeDonnees

Visiteur -> PageAccueil : Accéder à la page d'accueil
activate PageAccueil
PageAccueil -> BaseDeDonnees : Charger la vidéo de présentation
activate BaseDeDonnees
BaseDeDonnees --> PageAccueil : charger la vidéo et le texte de présentation est confirmé
deactivate BaseDeDonnees
PageAccueil --> Visiteur : Afficher la vidéo et le texte
deactivate PageAccueil
@enduml
