@startuml contact
actor Visiteur
participant PageContact
actor Administrateur as admin 

Visiteur -> PageContact : Accéder à la page de contact
activate PageContact
PageContact --> Visiteur : Affiche le formulaire de contact
Visiteur -> PageContact : soumettre et valider le formulaire de contact 
PageContact -> admin : envoyer le formulaire
admin --> PageContact : formulaire reçu
PageContact --> Visiteur : formulaire reçu
deactivate PageContact
@enduml
