@startuml Application_visiteur

left to right direction

actor Administrateur as Admin
actor Visiteur

rectangle Application_Ortholib {
    usecase (Accéder à la page d'accueil) as accueil 
    usecase (Voir la vidéo de présentation d'application et un texte) as VideoPresentation
    usecase (Accéder au menu) as menu
    usecase (Consulter la page de Contact ) as contact
    usecase (Consulter la page de présentation ) as Presentation
    usecase (consulter la liste des Orthophoniste proposées) as ListeOrthophonistes
    usecase (consulter sur le règlement de l'application) as ReglementApplication
    usecase (consulter les nouveautés de l'application) as NouveautesApplication
/'  usecase (Envoyer une des questions au formulaire de Contact ) as questionContact '/    
    usecase (S'inscrire) as inscription
    /' usecase (Recevoir un email de confirmation ) as emailConfirmation
    usecase (Saisir le code de confirmation) as codeConfirmation '/
    usecase (Validation d'un Compte) as Valider
    usecase (Compte active) as CompteActive
}

/' ACTOR -- USECASE'/
Visiteur -- accueil
Visiteur -- VideoPresentation
Visiteur -- menu
Visiteur -- Presentation
Visiteur -- ListeOrthophonistes
Visiteur -- ReglementApplication
Visiteur -- NouveautesApplication
Visiteur -- contact
Visiteur -- inscription
Admin -- Valider
Visiteur -- CompteActive


/' USECASE -- USECASE '/
accueil <.. VideoPresentation : include
accueil <.. menu : include
menu <.. Presentation : extends
menu <.. ReglementApplication : include
Presentation <.. ListeOrthophonistes : extends
Presentation <.. NouveautesApplication : extends
menu <.. contact : include
menu <.. inscription : include
inscription <.. Valider : include
Valider <.. CompteActive : include

@enduml