@startuml Application_Orthophoniste

left to right direction

actor Administrateur as Admin
actor Orthophoniste

rectangle Application_Ortholib {
    usecase "Accès à l’espace orthophonie" as EspaceOrthophonie
    usecase "Accéder à la liste des patients" as AccederListePatients
    usecase "Planifier une séance avec un patient" as PlanifierSeancePatient
    usecase "Consulter le profil d’un patient" as ConsulterProfilPatient
    usecase "Modifier le profil d’un patient" as ModifierProfilPatient
    usecase "Envoyer un message ou un fichier au patient" as EnvoyerMessageFichier
    usecase "Suivre la progression et noter le patient après une séance" as SuivreProgresNoterPatient
    usecase "Consulter les informations personnelles" as ConsulterInfos
    usecase "Mettre à jour les informations personnelles" as ModifierInfos
    usecase "Suivre le compteur des heures de séance" as SuivreCompteurHeuresSeance
    usecase "Consulter le nombre d'exercices personnalisés créés" as ConsulterNombreExercicesPersonnalises
    usecase "Visualiser la liste des exercices personnalisés" as VisualiserListeExercicesPersonnalises
    usecase "Assigner un exercice personnalisé à un patient" as AssignerExercicePersonnalisePatient
    usecase "Consulter la liste des exercices" as ConsulterListeExercices
    usecase "Afficher les détails d’un exercice" as AfficherDetailsExercice
    usecase "Consulter les patients ayant participé à un exercice" as ConsulterPatientsExercice
    usecase "Consulter les scores des patients sur un exercice spécifique" as ConsulterScoresExercice  
    usecase "Accéder à la liste des exercices personnalisables" as ListeExercicesPersonnalisables
    usecase "Personnaliser un exercice de vocabulaire" as PersonnaliserVocabulaire
    usecase "Personnaliser un exercice de mémoire" as PersonnaliserMemoire
    usecase "Personnaliser un exercice de dictée avec des mots et des fichiers audio" as PersonnaliserDicteeMotsAudio
    usecase "Sélectionner des patients pour un exercice personnalisé" as SelectionnerPatientsExercice
}

/' ACTORS -- ACTORS '/

Orthophoniste <- Admin

/' ACTORS -- USECASES '/

Orthophoniste -- EspaceOrthophonie
Orthophoniste -- AccederListePatients
Orthophoniste -- PlanifierSeancePatient
Orthophoniste -- ConsulterProfilPatient
Orthophoniste -- ModifierProfilPatient
Orthophoniste -- EnvoyerMessageFichier
Orthophoniste -- SuivreProgresNoterPatient
Orthophoniste -- ConsulterInfos
Orthophoniste -- ModifierInfos
Orthophoniste -- SuivreCompteurHeuresSeance
Orthophoniste -- ConsulterNombreExercicesPersonnalises
Orthophoniste -- VisualiserListeExercicesPersonnalises
Orthophoniste -- AssignerExercicePersonnalisePatient
Orthophoniste -- ConsulterListeExercices
Orthophoniste -- AfficherDetailsExercice
Orthophoniste -- ConsulterPatientsExercice
Orthophoniste -- ConsulterScoresExercice
Orthophoniste -- ListeExercicesPersonnalisables
Orthophoniste -- PersonnaliserVocabulaire
Orthophoniste -- PersonnaliserMemoire
Orthophoniste -- PersonnaliserDicteeMotsAudio
Orthophoniste -- SelectionnerPatientsExercice

/' USECASES -- USECASES '/

EspaceOrthophonie <.. AccederListePatients : include
AccederListePatients <.. PlanifierSeancePatient : include
PlanifierSeancePatient <.. ConsulterProfilPatient : include
ConsulterProfilPatient <.. ModifierProfilPatient : extend
EspaceOrthophonie <.. EnvoyerMessageFichier : extend
EspaceOrthophonie <.. SuivreProgresNoterPatient : include
EspaceOrthophonie <.. ConsulterInfos : include
ConsulterInfos <.. ModifierInfos : extend
ConsulterInfos <.. SuivreCompteurHeuresSeance : include
ConsulterInfos <.. ConsulterNombreExercicesPersonnalises : extend
ConsulterNombreExercicesPersonnalises <.. VisualiserListeExercicesPersonnalises : include
EspaceOrthophonie <.. VisualiserListeExercicesPersonnalises : include
VisualiserListeExercicesPersonnalises <.. AssignerExercicePersonnalisePatient : extend
EspaceOrthophonie <.. ConsulterListeExercices : extend
ConsulterListeExercices <.. AfficherDetailsExercice : include
AfficherDetailsExercice <.. ConsulterPatientsExercice : extend
ConsulterPatientsExercice <.. ConsulterScoresExercice : extend
EspaceOrthophonie <.. ListeExercicesPersonnalisables : include
ListeExercicesPersonnalisables <|-- PersonnaliserVocabulaire 
ListeExercicesPersonnalisables <|-- PersonnaliserMemoire 
ListeExercicesPersonnalisables <|-- PersonnaliserDicteeMotsAudio
ListeExercicesPersonnalisables <.. SelectionnerPatientsExercice : include

@enduml
