@startuml Ortholib_Class

abstract class User {
    - id : int
    - email : string
    - roles : array
    - password : string
    - nom : string
    - prenom : string
    - telephone : string
    - createdAt : DateTimeImmutable
    - genre : string
    - ville : string

    + getId() : int
    + getEmail() : string
    + setEmail(email: string) : self
    + getUserIdentifier() : string
    + getRoles() : array
    + setRoles(roles: array) : self
    + getPassword() : string
    + setPassword(password: string) : self
    + eraseCredentials() : void
    + getNom() : string
    + setNom(nom: string) : self
    + getPrenom() : string
    + setPrenom(prenom: string) : self
    + getTelephone() : string
    + setTelephone(telephone: string) : self
    + getCreatedAt() : DateTimeImmutable
    + setCreatedAt(createdAt: DateTimeImmutable) : self
    + getGenre() : string
    + setGenre(genre: string) : self
    + getVille() : string
    + setVille(ville: string) : self
    + __toString() : string
}

class Administrateur {
    + getRoles() : Array
}

class Orthophoniste {
    - nombreHeureTravail : int
    - patients : Collection<Patient>
    - cabinet : Collection<Cabinet>
    - imagesOrthophoniste : Collection<Image>
    - specialisation : String
    - seances : Collection<Seances>
    - exercices : Collection<Exercice>

    + getNombreHeureTravail() : int
    + setNombreHeureTravail(nombreHeureTravail : int)
    + getRoles() : Array
    + getPatients() : Collection<Patient>
    + addPatient(patient : Patient)
    + removePatient(patient : Patient)
    + getCabinet() : Collection<Cabinet>
    + setCabinet(cabinet : Collection<Cabinet>)
    + getImagesOrthophoniste() : Collection<Image>
    + addImageOrthophoniste(imagesOrthophoniste : Image)
    + removeImageOrthophoniste(imagesOrthophoniste : Image)
    + getSpecialisation() : String
    + setSpecialisation(specialisation : String)
    + getSeances() : Collection<Seances>
    + addSeance(seances : Seances)
    + removeSeance(seances : Seances)
    + getExercices() : Collection<Exercice>
    + addExercice(exercices : Exercice)
    + removeExercice(exercices : Exercice)
}

class Patient {
    - niveauLangue : String
    - difficulteTest : String
    - niveauApprentissage : String
    - deficient : String
    - difficulteRencontrees : Array
    - choixOrtho : Collection<Orthophoniste>
    - imagesPatient : Collection<Image>
    - seances : Collection<Seances>
    - exercices : Collection<Exercice>
    - resultatExercices : Collection<ResultatExercice>

    + getNiveauLangue() : String
    + setNiveauLangue(niveauLangue : String)
    + getDifficulteTest() : String
    + setDifficulteTest(difficulteTest : String)
    + getNiveauApprentissage() : String
    + setNiveauApprentissage(niveauApprentissage : String)
    + getDeficient() : String
    + setDeficient(deficient : String)
    + getRoles() : Array
    + getDifficultesRencontrees() : Array
    + setDifficultesRencontrees(difficultesRencontrees : Array)
    + getChoixOrtho() : Collection<Orthophoniste>
    + setChoixOrtho(choixOrtho : Collection<Orthophoniste>)
    + getImagesPatient() : Collection<Image>
    + addImagesPatient(imagesPatient : Image)
    + removeImagesPatient(imagesPatient : Image)
    + getSeances() : Collection<Seances>
    + addSeance(seances : Seances)
    + removeSeance(seances : Seances)
    + getExercices() : Collection<Exercice>
    + addExercice(exercices : Exercice)
    + removeExercice(exercices : Exercice)
    + getResultatExercices() : Collection<ResultatExercice>
    + addResultatExercice(resultatExercices : ResultatExercice)
    + removeResultatExercice(resultatExercices : ResultatExercice)
}

class Cabinet {
    - id : int
    - nom : String
    - adresse : String
    - telephone : String
    - orthophonistes : Collection<Orthophoniste>
    - imagesCabinet : Collection<Image>

    + getId() : int
    + getNom() : String
    + setNom(nom : String)
    + getAdresse() : String
    + setAdresse(adresse : String)
    + getTelephone() : String
    + setTelephone(telephone : String)
    + getOrthophonistes() : Collection<Orthophoniste>
    + addOrthophoniste(orthophonistes : Orthophoniste)
    + removeOrthophoniste(orthophonistes : Orthophoniste)
    + getImagesCabinet() : Collection<Image>
    + addImagesCabinet(imagesCabinet : Image)
    + removeImagesCabinet(imagesCabinet : Image)
}

class Exercice {
    - id : int
    - type : String
    - chronometre : Patient
    - patient : Collection<Patient>
    - orthophoniste : Collection<Orthophoniste>
    - signification : Collection<Signification>
    - resultatExercices : Collection<ResultatExercice>

    + getId() : int
    + getType() : String
    + setType(type : String)
    + getChronometre() : int
    + setChronometre(chronometre : int)
    + getPatient() : Collection<Patient>
    + setPatient(patient : Collection<Patient>)
    + getOrthophoniste() : Collection<Orthophoniste>
    + setOrthophoniste(orthophoniste : Collection<Orthophoniste>)
    + getSignification() : Collection<Signification>
    + addSignification(signification : Signification)
    + removeSignification(signification : Signification)
    + getResultatExercices() : Collection<ResultatExercice>
    + addResultatExercice(resultatExercices : ResultatExercice)
    + removeResultatExercice(resultatExercices : ResultatExercice)
}

class Image {
    - id : int
    - name : String
    - cabinet : Collection<Cabinet>
    - orthophoniste : Collection<Orthophoniste>
    - patient : Collection<Patient>

    + getId() : int
    + getName() : String
    + setName(name : String)
    + getCabinet() : Collection<Cabinet>
    + setCabinet(cabinet : Collection<Cabinet>)
    + getOrthophoniste() : Collection<Orthophoniste>
    + setOrthophoniste(orthophoniste : Collection<Orthophoniste>)
    + getPatient() : Collection<Patient>
    + setPatient(patient : Collection<Patient>)
}

class ResultatExercice {
    - id : int
    - exercice : Collection<Exercice>
    - patient : Collection<Patient>
    - score : int
    - date : DateTimeInterface

    + getId() : int
    + getExercice() : Collection<Exercice>
    + setExercice(exercice : Collection<Exercice>)
    + getPatient() : Collection<Patient>
    + setPatient(patient : Collection<Patient>)
    + getScore() : int
    + setScore(score : int)
    + getDate() : DateTimeInterface
    + setDate(date : DateTimeInterface)
}

class Seances {
    - id : int
    - orthophoniste : Orthophoniste
    - patient : Patient
    - dateHeureDebut : DateTimeInterface
    - dateHeureFin : DateTimeInterface
    - mode : string
    - duree : string
    - exercices : string

    + getId() : int
    + getOrthophoniste() : Orthophoniste
    + setOrthophoniste(orthophoniste: Orthophoniste) : self
    + getPatient() : Patient
    + setPatient(patient: Patient) : self
    + getDateHeureDebut() : DateTimeInterface
    + setDateHeureDebut(dateHeureDebut: DateTimeInterface) : self
    + getDateHeureFin() : DateTimeInterface
    + setDateHeureFin(dateHeureFin: DateTimeInterface) : self
    + getMode() : string
    + setMode(mode: string) : self
    + getDuree() : int
    + setDuree(duree: int) : self
    + calculerTotalHeures(seances: array) : int
    + verifierLimiteHeures(seances: array) : bool
    + getExercices() : string
    + setExercices(exercices: string) : self
}

class Orthophoniste
class Patient

Seances --> Orthophoniste : appartient à
Seances --> Patient : appartient à


Utilisateur <|-- Orthophoniste
Utilisateur <|-- Patient
Utilisateur <|-- Administrateur
Utilisateur <|-- Secretaire

Cabinet "1" -- "0..*" Orthophoniste : emploie
Cabinet "1" -- "0..1" Secretaire : a

Orthophoniste "1" -- "0..*" Patient : suit
Patient "0..*" -- "0..*" Jeu : participe
Patient "1" -- "0..*" ExercicePersonnalise : suit
Compte "1" -- "0..*" ExercicePersonnalise : contient
Compte "1" -- "0..*" Jeu : contient
Compte "1" -- "1" Utilisateur : appartient à

@enduml